################################################################################

# This Makefile generated by GoMakeGen 0.8.0 using next command:
# gomakegen --metalinter .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt deps-test test metalinter help

################################################################################

deps-test: ## Download dependencies for tests
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/check.v1

test: ## Run tests
	go test -covermode=count .

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

metalinter: ## Install and run gometalinter
	test -s $(GOPATH)/bin/gometalinter || (go get -u github.com/alecthomas/gometalinter ; $(GOPATH)/bin/gometalinter --install)
	$(GOPATH)/bin/gometalinter --deadline 30s

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
