name: GoDoc

on:
  create

jobs:
  GoSumDB:
    name: Trigger GoSum/PkgGoDev
    runs-on: ubuntu-latest

    env:
      GO_SUM: https://sum.golang.org/lookup
      GO_PKG: https://pkg.go.dev/fetch

    steps:
      - name: Send requests to GoSum DB and PkgGoDev
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]] ; then
            full_ver=$(echo ${GITHUB_REF} | cut -f3 -d'/')
            major_ver=$(echo ${full_ver} | cut -f1 -d'.')
            echo "FULL: ${full_ver} | MAJOR: ${major_ver}"
            curl -s -m 15 ${{env.GO_SUM}}/pkg.re/${{github.repository}}.${major_ver}@${full_ver}+incompatible
            curl -s -m 15 -X POST ${{env.GO_PKG}}/pkg.re/${{github.repository}}.${major_ver}@${full_ver}+incompatible
          fi
